### ISSUE TITLE
Use a logo without a transparent background

### ISSUE THREAD

**Issue by spkane** [superorbital/.github#1]
The logo is basically unreadable if anyone is using dark mode.

![image](https://github.com/superorbital/.github/assets/129629/f6afa84f-b06d-4c0c-b0df-dca00ae3e811)

**Comment by tammersaleh** [comment]
agreed - wanna PR?

**Comment by spkane** [comment]
Yeah, I'm happy to. It was just something I came across while doing other work, so I was documenting it and trying to stay focused on the task at hand. I'll put in a PR tomorrow.
